server:
  port: 8503
spring:
  boot:
    admin:
      client:
        url: http://localhost:9999
  application:
    name: task-service
  cloud:
    consul:
      discovery:
        register: true
        service-name: task-service
      host: localhost
      port: 8500
  datasource:
    url: jdbc:mysql://localhost:3306/hr
    username: root
    password: Root@1234
    driver-class-name: 